""" model building  update

Revision ID: 25b337a58128
Revises: 7062f4dcac1d
Create Date: 2026-07-19 11:46:06.709281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b337a58128'
down_revision: Union[str, Sequence[str], None] = '7062f4dcac1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buidings', sa.Column('buildung_name', sa.String(), nullable=True))
    op.add_column('buidings', sa.Column('buildung_code', sa.String(), nullable=False))
    op.drop_constraint(op.f('buidings_code_key'), 'buidings', type_='unique')
    op.create_unique_constraint(None, 'buidings', ['buildung_name'])
    op.create_unique_constraint(None, 'buidings', ['buildung_code'])
    op.drop_column('buidings', 'name')
    op.drop_column('buidings', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buidings', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('buidings', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buidings', type_='unique')
    op.drop_constraint(None, 'buidings', type_='unique')
    op.create_unique_constraint(op.f('buidings_code_key'), 'buidings', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('buidings', 'buildung_code')
    op.drop_column('buidings', 'buildung_name')
    # ### end Alembic commands ###
