""" model floor  update

Revision ID: 2bbf1d612de6
Revises: dcd1ae9d824d
Create Date: 2026-07-19 14:40:38.845518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbf1d612de6'
down_revision: Union[str, Sequence[str], None] = 'dcd1ae9d824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('building_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('floors_buiding_id_fkey'), 'floors', type_='foreignkey')
    op.create_foreign_key(None, 'floors', 'buidings', ['building_id'], ['id'], ondelete='CASCADE')
    op.drop_column('floors', 'buiding_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('buiding_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.create_foreign_key(op.f('floors_buiding_id_fkey'), 'floors', 'buidings', ['buiding_id'], ['id'], ondelete='CASCADE')
    op.drop_column('floors', 'building_id')
    # ### end Alembic commands ###
