-- Active: 1784292664588@@127.0.0.1@5432@campuscompass
"""initial model schemaupdate

Revision ID: 9bf758169939
Revises: 548204833ba7
Create Date: 2026-07-18 12:25:31.947250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf758169939'
down_revision: Union[str, Sequence[str], None] = '548204833ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
