""" model building  update

Revision ID: 9e501dd83a84
Revises: 25b337a58128
Create Date: 2026-07-19 12:00:43.192818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e501dd83a84'
down_revision: Union[str, Sequence[str], None] = '25b337a58128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buidings', sa.Column('building_name', sa.String(), nullable=True))
    op.add_column('buidings', sa.Column('building_code', sa.String(), nullable=False))
    op.drop_constraint(op.f('buidings_buildung_code_key'), 'buidings', type_='unique')
    op.drop_constraint(op.f('buidings_buildung_name_key'), 'buidings', type_='unique')
    op.create_unique_constraint(None, 'buidings', ['building_code'])
    op.create_unique_constraint(None, 'buidings', ['building_name'])
    op.drop_column('buidings', 'buildung_code')
    op.drop_column('buidings', 'buildung_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buidings', sa.Column('buildung_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('buidings', sa.Column('buildung_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'buidings', type_='unique')
    op.drop_constraint(None, 'buidings', type_='unique')
    op.create_unique_constraint(op.f('buidings_buildung_name_key'), 'buidings', ['buildung_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('buidings_buildung_code_key'), 'buidings', ['buildung_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('buidings', 'building_code')
    op.drop_column('buidings', 'building_name')
    # ### end Alembic commands ###
