"""initial database schemaupdate

Revision ID: a1bda46b1e5a
Revises: ac2116d31d99
Create Date: 2026-07-18 00:35:26.868495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bda46b1e5a'
down_revision: Union[str, Sequence[str], None] = 'ac2116d31d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('buidings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('buidings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('floors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('floors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('floors', 'updated_at')
    op.drop_column('floors', 'created_at')
    op.drop_column('buidings', 'updated_at')
    op.drop_column('buidings', 'created_at')
    op.drop_column('audits', 'updated_at')
    # ### end Alembic commands ###
