"""initial database schema

Revision ID: ac2116d31d99
Revises: 06c85be9d294
Create Date: 2026-07-17 23:56:49.450673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2116d31d99'
down_revision: Union[str, Sequence[str], None] = '06c85be9d294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'rooms', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
