""" model floor  update

Revision ID: c13aa4b0a5d3
Revises: 4e5f811ff033
Create Date: 2026-07-20 00:19:40.284847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13aa4b0a5d3'
down_revision: Union[str, Sequence[str], None] = '4e5f811ff033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('locations', 'longtide')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('longtide', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('locations', 'longitude')
    # ### end Alembic commands ###
