""" model floor  update

Revision ID: dc7c4bcef196
Revises: 429fe083c909
Create Date: 2026-07-19 16:49:09.756142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7c4bcef196'
down_revision: Union[str, Sequence[str], None] = '429fe083c909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'rooms', ['room_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'floor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
