""" model floor  update

Revision ID: f998ea630c8c
Revises: 2bbf1d612de6
Create Date: 2026-07-19 14:57:12.087606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f998ea630c8c'
down_revision: Union[str, Sequence[str], None] = '2bbf1d612de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'floors', ['floor_number'])
    op.create_unique_constraint(None, 'floors', ['floor_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'floors', type_='unique')
    op.drop_constraint(None, 'floors', type_='unique')
    # ### end Alembic commands ###
